name: home_services
description: home_services customer app

publish_to: 'none'
version: 1.0.5+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^3.26.0
  get_storage: ^1.4.0
  dio: ^3.0.10
  dio_http_cache: ^0.2.11
  google_fonts: ^1.1.2
  cached_network_image: ^2.5.0
  carousel_slider: ^3.0.0
  flutter_svg: ^0.19.3

  firebase_messaging: ^7.0.3
  cloud_firestore: ^0.14.1+3
  cloud_firestore_web: ^0.2.0+5
  firebase_auth: ^0.18.1+2
  firebase_auth_web: ^0.3.0
  firebase_core: ^0.5.1
  firebase_storage: ^5.2.0

  flutter_staggered_grid_view: ^0.3.4
  webview_flutter: ^1.0.7
  google_map_location_picker: ^4.1.2+1
  google_maps_flutter: ^1.2.0
  flutter_html: ^1.2.0
  url_launcher: ^5.7.10

  geocoding: ^1.0.5
  geolocator: ^6.1.1

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - config/
    - assets/img/
    - assets/icon/
    - assets/locales/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
